website:
  sidebar:
    style: "floating"
    collapsible: true
    search: false
    tools:
      - icon: github
        href: https://github.com/ruslan-basyrov/acuity

project:
  type: acuity

format:
  acuity-html:
    respect-user-color-scheme: true
  acuity-typst: default
